### ISSUE TITLE
Crypto Module?

### ISSUE THREAD

**Issue by whitedavidp** [MageLuingil/tasker-commonjs#2]
Hello and thanks for this great idea!

I know this is outside the scope of things, but thought perhaps you would know as I am new to JS, node, etc.

I am trying to use JS to decrypt and I have the crypto-js module and have put it into place as directed and require seems to find it. However, the code seems to also require the crypto module and that seems to be a part of node now rather than a distinct module (and perhaps has the need for native library support as well.

Are you aware of any way I can do this?

Thanks!

**Comment by MageLuingil** [comment]
You're correct, the `crypto` module is [part of node.js](https://nodejs.org/api/crypto.html), so sadly it's not available in the WebView that Tasker uses. I haven't heard of any way to get node libraries working in Tasker, so you'll need to find another crypto library that can be run in-browser only (without node support). I've done very little with crypto in js, so I'm afraid I can't help you there.

A quick bit of Google-fu brought up [this native js library](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/decrypt) that _might_ be available in your WebView; you may be able to use that, provided you're working with common RSA/AES ciphers. It's worth taking a look at least.

**Comment by whitedavidp** [comment]
Thanks so much for your fine work and help here.
